### PR TITLE
Added height attribute and scaling instructions.

### PR DESCRIPTION
**Pull request by emartinez-usgs**
Fixes some scaling issues in IE. Seems not to introduce any regressions. Feel free to implement otherwise.

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
Is there a reason you chose `768` instead of using the `height` variable?

**Comment by emartinez-usgs** [comment]
It looks like it scales it up until the height attribute value is reached, but not before. The default height value left top/bottom padding around the SVG when the window was otherwise still at a reasonable size. Using 768 gave a broader scaling range. Feel free to switch it to use the height property.

**Comment by jmfee-usgs** [comment]
What happens once the height goes past 768?  Maybe `width="100%"`?

**Comment by emartinez-usgs** [comment]
Specifying width of any sort seemed to break scaling altogether.

**Pull request merged**
